# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mixtape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('played_count', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mixtapes', to=settings.AUTH_USER_MODEL)),
                ('saved_users', models.ManyToManyField(related_name='saved_mixtapes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mixtape',
            name='songs',
            field=models.ManyToManyField(related_name='_mixtape_songs_+', to='mixer.Song'),
        ),
    ]
