# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mixtape',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='mixtape',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='mixer.Mixtape'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
