# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0002_auto_20171126_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixtape',
            name='played_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
